<?xml version="1.0" encoding="utf-8"?><Database Name="DBBETTERLIFESERVER" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=41.38.119.3;Initial Catalog=DBBETTERLIFESERVER;User ID=ba;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="tnerhbeauty.Properties.Settings" SettingsPropertyName="DBBETTERLIFE_MDF" Provider="System.Data.SqlClient" />
  <Table Name="dbo.amount_client" Member="amount_clients">
    <Type Name="amount_client">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_client" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="amount_in" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="amount_out" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="nots" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Source_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.amount_client_type" Member="amount_client_types">
    <Type Name="amount_client_type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="nots" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="list_price" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.company_info" Member="company_infos">
    <Type Name="company_info">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Specialized_in" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="hedar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="footer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="nots" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.fara" Member="faras">
    <Type Name="fara">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_fara" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.invoice_type" Member="invoice_types">
    <Type Name="invoice_type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_invoice_type" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="frm_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceDetails" Member="InvoiceDetails">
    <Type Name="InvoiceDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InvoiceHeaderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceHeader" Member="InvoiceHeaders">
    <Type Name="InvoiceHeader">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cient" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount_percent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Extra_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Extra_percent" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Extra" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total_product" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Net" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="is_agel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_invoice_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.list_price" Member="list_prices">
    <Type Name="list_price">
      <Column Name="id" Type="System.String" DbType="NVarChar(300) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_row" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.setting" Member="settings">
    <Type Name="setting">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="show_invoice_pay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_invoice_pay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_invoice_pay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_invoice_pay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_invoice_sale" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_invoice_sale" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_invoice_sale" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_invoice_sale" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_invoice_to_stroe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_invoice_to_stroe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_invoice_to_stroe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_invoice_to_stroe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_product" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_product" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_product" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_product" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_price_producut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_price_producut_exal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="kashf_hesab_prodct" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="blance_in_storses" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="store_in_and_out" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="report_mabeat_product" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_amount_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_amount_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_amount_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_amount_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="kashf_hesab_client" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_fara" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_fara" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_fara" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_fara" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_store" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_store" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_store" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_store" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_user" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_user" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_user" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_user" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_setting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_setting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_setting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_setting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_company" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show_InvoiceHeader_wait" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="add_InvoiceHeader_wait" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="update_InvoiceHeader_wait" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delete_InvoiceHeader_wait" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.store" Member="stores">
    <Type Name="store">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.store_log" Member="store_logs">
    <Type Name="store_log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty_in" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty_out" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="nots" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Source_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="id_setting" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.amount_client_View" Member="amount_client_Views">
    <Type Name="amount_client_View">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_client" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="name_client" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_type" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="amount_in" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="amount_out" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(19,2) NOT NULL" CanBeNull="false" />
      <Column Name="nots" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Source_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="name_fara" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Balance_product_store_View" Member="Balance_product_store_Views">
    <Type Name="Balance_product_store_View">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.client_View" Member="client_Views">
    <Type Name="client_View">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="nots" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="name_row" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="list_price" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2) NOT NULL" CanBeNull="false" />
      <Column Name="Balance_type" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_fara" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceDetails_rep_View" Member="InvoiceDetails_rep_Views">
    <Type Name="InvoiceDetails_rep_View">
      <Column Name="InvoiceHeaderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="namepro" Type="System.String" DbType="NVarChar(401) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceHeaderView" Member="InvoiceHeaderViews">
    <Type Name="InvoiceHeaderView">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="id_cient" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Total_product" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Extra" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Net" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="is_agel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_invoice_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_invoice_type" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_fara" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceHeaderView_in" Member="InvoiceHeaderView_ins">
    <Type Name="InvoiceHeaderView_in">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="name_invoice_type" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="id_invoice_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_fara" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.prodcut_get_View" Member="prodcut_get_Views">
    <Type Name="prodcut_get_View">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="id_cient" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Client_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="is_agel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.product_serch_seore_Viewaa" Member="product_serch_seore_Viewaas">
    <Type Name="product_serch_seore_Viewaa">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(401) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_100" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_75" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_vip2" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_vip1" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_1" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_2" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_3" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_4" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_5" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_6" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_7" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_8" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_9" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_10" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="update_price" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,3) NOT NULL" CanBeNull="false" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.store_log_Balance_View" Member="store_log_Balance_Views">
    <Type Name="store_log_Balance_View">
      <Column Name="code" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Balance_sabk" Type="System.Decimal" DbType="Decimal(3,3) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty_in" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty_out" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(3,3) NOT NULL" CanBeNull="false" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.store_log_View" Member="store_log_Views">
    <Type Name="store_log_View">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAdd" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="name_invoice_type" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty_in" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty_out" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(19,3) NOT NULL" CanBeNull="false" />
      <Column Name="nots" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Source_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.store_View" Member="store_Views">
    <Type Name="store_View">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_fara" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.user_View" Member="user_Views">
    <Type Name="user_View">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="adress" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="id_fara" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_fara" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="id_setting" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name_setting" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateServer" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="user_Add" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InvoiceDetails_View" Member="InvoiceDetails_Views">
    <Type Name="InvoiceDetails_View">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceHeaderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(401)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="price_buy" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_100" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_75" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_vip2" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_vip1" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_1" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_2" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_3" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_4" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_5" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_6" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_7" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_8" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_9" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_10" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="min_mum" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="update_price" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="category" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.product_serch_View" Member="product_serch_Views">
    <Type Name="product_serch_View">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(401) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_100" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_75" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_vip2" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_sale_vip1" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_1" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_2" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_3" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_4" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_5" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_6" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_7" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_8" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_9" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="price_10" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="update_price" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,3) NOT NULL" CanBeNull="false" />
      <Column Name="min_mum" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="store_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="is_stop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.product_min_mum_View" Member="product_min_mum_Views">
    <Type Name="product_min_mum_View">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(401) NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,3) NOT NULL" CanBeNull="false" />
      <Column Name="min_mum" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="want" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
    </Type>
  </Table>
</Database>